
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TK_PRINTLN = 8;
  public static final int MULT = 17;
  public static final int CHAR = 6;
  public static final int LLAVE2 = 38;
  public static final int EQUALS = 27;
  public static final int LLAVE1 = 37;
  public static final int XOR = 30;
  public static final int DOUBLE = 10;
  public static final int INT = 9;
  public static final int FOR = 39;
  public static final int IGUAL2 = 21;
  public static final int NOT = 31;
  public static final int FINCADENA = 7;
  public static final int AND = 29;
  public static final int IGUAL = 32;
  public static final int OR = 28;
  public static final int BOOL = 36;
  public static final int DIV = 18;
  public static final int IF = 35;
  public static final int UMENOS = 16;
  public static final int ID = 5;
  public static final int EOF = 0;
  public static final int DECIMAL = 4;
  public static final int TRUE = 33;
  public static final int error = 1;
  public static final int CADENA = 2;
  public static final int MODULO = 20;
  public static final int MENOS = 15;
  public static final int MENOR = 23;
  public static final int PAR_C = 13;
  public static final int ENTEROS = 3;
  public static final int PAR_A = 12;
  public static final int MAYORIQ = 26;
  public static final int MAYOR = 24;
  public static final int POTENCIA = 19;
  public static final int NEGAR = 22;
  public static final int MENORIQ = 25;
  public static final int STRING = 11;
  public static final int FALSE = 34;
  public static final int MAS = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CADENA",
  "ENTEROS",
  "DECIMAL",
  "ID",
  "CHAR",
  "FINCADENA",
  "TK_PRINTLN",
  "INT",
  "DOUBLE",
  "STRING",
  "PAR_A",
  "PAR_C",
  "MAS",
  "MENOS",
  "UMENOS",
  "MULT",
  "DIV",
  "POTENCIA",
  "MODULO",
  "IGUAL2",
  "NEGAR",
  "MENOR",
  "MAYOR",
  "MENORIQ",
  "MAYORIQ",
  "EQUALS",
  "OR",
  "AND",
  "XOR",
  "NOT",
  "IGUAL",
  "TRUE",
  "FALSE",
  "IF",
  "BOOL",
  "LLAVE1",
  "LLAVE2",
  "FOR"
  };
}

